<?php
return array(
	array(
		'title' => 'Search books',
		'description' => 'Search books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.search-books',
	),
	array(
		'title' => 'Search posts',
		'description' => 'Search posts',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.search-posts',
	),
	array(
		'title' => 'Search works',
		'description' => 'Search works',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.search-works',
	),
	array(
		'title' => 'Book categories',
		'description' => 'Book categories',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-categories',
	),
	array(
		'title' => 'Book profile',
		'description' => 'Book profile',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.profile-book',
		'requirements' => array('subject' => 'book'),
	),
	array(
		'title' => 'Post profile',
		'description' => 'Post profile',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.profile-post',
		'requirements' => array('subject' => 'post'),
	),
	array(
		'title' => 'Book profile photos',
		'description' => 'Book profile photos',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.profile-book-photos',
		'requirements' => array('subject' => 'book'),
	),
	array(
		'title' => 'Book\'s readers\' feelings',
		'description' => 'Book\'s readers\' feelings',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.book-reader-feelings',
		'isPaginated' => true,
		'requirements' => array('subject' => 'book'),
	),
	array(
		'title' => 'Post profile book photos',
		'description' => 'Post profile book photos',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.post-profile-book-photos',
		'isPaginated' => true,
		'requirements' => array('subject' => 'book_post'),
	),
	array(
		'title' => 'Post profile book',
		'description' => 'Post profile book',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.post-profile-book',
		'isPaginated' => true,
		'requirements' => array('subject' => 'book_post'),
	),
	array(
		'title' => 'Listing books',
		'description' => 'Listing books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-books'
	),
	array(
		'title' => 'Newest books',
		'description' => 'Newest books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.newest-books',
		'isPaginated' => true,
	),
	array(
		'title' => 'Newest works',
		'description' => 'Newest works',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.newest-works',
		'adminForm' => array(
            'elements' => array(
                array(
                    'Text',
                    'numberOfWorks',
                    array(
                        'label' => 'Number of newest works',
                        'value' => '5',
                        'validators' => array(
                            array('Int', true),
                            array('GreaterThan', true, array(0)),
                        )
                    )
                ),
            )
        ),
	),
	array(
		'title' => 'Highest rating books',
		'description' => 'Highest rating books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.highest-rating-books',
		'isPaginated' => true,
	),
	array(
		'title' => 'Popular books',
		'description' => 'Popular books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.popular-books',
		'isPaginated' => true,
	),
	array(
		'title' => 'Random books',
		'description' => 'Random books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.random-books',
		'isPaginated' => true,
	),
	array(
		'title' => 'Book Browse Quick Menu',
		'description' => 'Displays a small menu in the book browse page.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.browse-menu-quick'
	),
	array(
		'title' => 'Profile Menu Book',
		'description' => 'Displays a small menu in the book profile page.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.profile-menu-book'
	),
	array(
		'title' => 'Browse Posts Of User',
		'description' => 'Displays a small random book list of a user.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.posts-of-user',
	),
	array(
		'title' => 'Browse Posts Of Book',
		'description' => 'Displays a small random book list relating a book.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.posts-of-book'
	),
	array(
		'title' => 'List of random authors',
		'description' => 'Displays a random list of authors.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-random-authors',
		'isPaginated' => true,
	),
	array(
		'title' => 'List of random publishers',
		'description' => 'Displays a random list of publishers.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-random-publishers',
		'isPaginated' => true,
	),
	array(
		'title' => 'List of random books',
		'description' => 'Displays a random list of books.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-random-books',
	),
	array(
		'title' => 'List of random works',
		'description' => 'Displays a random list of works.',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-random-works',
		'isPaginated' => true,
		'defaultParams' => array(
      		'title' => 'Random works',
	    ),
	),
	array(
		'title' => 'Books of an author',
		'description' => 'Displays a random list books of an author',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.books-of-author',
		'isPaginated' => true,		
	),
	array(
		'title' => 'Mange book\'s photos',
		'description' => 'Mange book\'s photo. Only admin, book author or the person posted this book see this widget',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.manage-book-photos',
		'requirements' => array(
            'subject' => 'book',
        ),
	),
	array(
		'title' => 'User\'s favorite books',
		'description' => 'This widget lists all user\'s favorite books',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.fav-books-of-user',
		'requirements' => array(
            'subject' => 'user',
        ),
	),
	array(
		'title' => 'Owner photo',
		'description' => 'This widget shows the photo of the owner of suject',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.owner-photo',
	),
	array(
		'title' => 'Owner info',
		'description' => 'This widget shows the general information of the owner of suject',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.owner-info',
	),
	array(
		'title' => 'Owner fields',
		'description' => 'This widget shows the profile information of the owner of suject',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.owner-fields',
	),
	array(
		'title' => 'Profile work',
		'description' => 'This widget shows the information of a work',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.profile-work',
	),
	array(
		'title' => 'List chapters',
		'description' => 'This widget shows a list of chapters. This widget is used in the chapter detail page',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-chapters',
	),
	array(
		'title' => 'My published books',
		'description' => 'This widget shows a list of books that user published',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.my-published-books',
		'requirements' => array(
            'subject' => 'user',
        ),
	),
	array(
		'title' => 'My wooks',
		'description' => 'This widget shows a list of works of the user',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.my-works',
		'requirements' => array(
            'subject' => 'user',
        ),
	),
	array(
		'title' => 'Random users',
		'description' => 'This widget shows a list of random users',
		'category' => 'Books',
		'type' => 'widget',
		'name' => 'book.list-random-users',
	),
);